blank_issues_enabled: false
contact_links:
    - name: Tool Submission
      url: https://www.powerplatformtoolbox.com/submit-tool
      about: Submit a tool to be included in the Power Platform ToolBox.

    - name: PPTB Community Support
      url: https://discord.gg/efwAu9sXyJ
      about: Join the Discord community for help and support.
