blank_issues_enabled: false
contact_links:
    - name: Tool Submission
      url: https://github.com/PowerPlatformToolBox/pptb-web/issues/new?template=tool-submission.yml
      about: Submit a tool to be included in the Power Platform Tool Box.

    - name: PPTB Community Support
      url: https://github.com/PowerPlatformToolBox/desktop-app/discussions
      about: Please ask and answer questions here.
